#!/bin/sh

# Load hub ( https://hub.github.com )
eval "$(hub alias -s)"
fpath=($DIR/zsh/completions $fpath)
autoload -U compinit && compinit

alias gpr="git-pull-request"
git-pull-request() {
	local BASE
}

alias grm="git-rebase-master"
git-rebase-master() {
	local ORIGIN
	local BRANCH
	ORIGIN="$1"
	BRANCH="$2"
	test -z "$ORIGIN" && ORIGIN="origin"
	test -z "$BRANCH" && BRANCH="master"

    git fetch "$ORIGIN"
	git rebase "${ORIGIN}/${BRANCH}"
}

alias gmu="git-merge-upstream"
git-merge-upstream() {
	branch="$1"
	test -z "$branch" && branch="master"
	git fetch upstream
	git merge upstream/$branch
}

gitclean() {
    git delete-merged-branches
    git gc
}

gitcleandir() {
    local DIR
    DIR="`pwd`"
    echo "Start dir is $DIR"
    IFS="
"
    for i in `ls`; do
        if [ -d "$i" ]; then
            echo "Changing into $i"
            builtin cd "$i"
            if [ -d ".git" ]; then
                gitclean
            fi
            builtin cd "$DIR"
        fi
    done
}
